### PR TITLE
Adds blog page and publishes to Heroku

### PR DESCRIPTION
**Pull request by finnhodgkin**
I can't assign @shouston3 yet, guessing he hasn't been added to the org yet :cry: 

Sorry this PR is rather large. Changes:

* Adds a basic navbar to all pages including the home (so we could access the blog from the home)
* Adds user images and bios so blog posts have authors
* Sets up a .env file with a MONGODB_URI that defaults to the standard local mongo address if no environment variable is present
* Adds a blog card widget to all articles page that can be browsed for related posts or posts with the same tag

#8 #7 #4

### CODE REVIEW

**Comment by iteles** [comment]
Just hasn't accepted the invitation yet 😊 @shouston3 Let me know if you need me to send it again!

**Comment by Cleop** [comment]
@shouston3 - yep, you're seeing the right thing! We were focussing on functionality yesterday so it's pretty bare right now. Now that we've hooked up the db to Heroku I'll also be adding more content too.

**Comment by shouston3** [comment]
I'm really glad it's bare, the smaller the prs the better. Looks great. I would say to keep focusing on functionality for now

**Comment by shouston3** [comment]
Just received the heroku invite

**Comment by Cleop** [comment]
@shouston3 - are you still in-review on this one?

**Comment by shouston3** [comment]
yes

**Pull request merged**
